template Host "lab-fast-host" {
  check_command = "ssh"
  max_check_attempts = 2
  check_interval = 10s
  retry_interval = 3s
  enable_notifications = false

  vars.ssh_port = 22
  vars.ssh_timeout = 5
  vars.lab_managed = true
  vars.lab_ssh_user = "operator"
  vars.lab_remote_command = "/usr/local/libexec/check_lab_middleware"
}

object Host "lab-prod-app01" {
  import "lab-fast-host"
  address = "lab-prod-app01"
  display_name = "PROD / APP 01"
  vars.lab_environment = "prod"
  vars.lab_role = "app"
}

object Host "lab-prod-app02" {
  import "lab-fast-host"
  address = "lab-prod-app02"
  display_name = "PROD / APP 02"
  vars.lab_environment = "prod"
  vars.lab_role = "app"
}

object Host "lab-prod-web01" {
  import "lab-fast-host"
  address = "lab-prod-web01"
  display_name = "PROD / WEB 01"
  vars.lab_environment = "prod"
  vars.lab_role = "web"
}

object Host "lab-prod-mq01" {
  import "lab-fast-host"
  address = "lab-prod-mq01"
  display_name = "PROD / MQ 01"
  vars.lab_environment = "prod"
  vars.lab_role = "mq"
}

object Host "lab-test-app01" {
  import "lab-fast-host"
  address = "lab-test-app01"
  display_name = "TEST / APP 01"
  vars.lab_environment = "test"
  vars.lab_role = "app"
}

object Host "lab-test-web01" {
  import "lab-fast-host"
  address = "lab-test-web01"
  display_name = "TEST / WEB 01"
  vars.lab_environment = "test"
  vars.lab_role = "web"
}

object Host "lab-test-mq01" {
  import "lab-fast-host"
  address = "lab-test-mq01"
  display_name = "TEST / MQ 01"
  vars.lab_environment = "test"
  vars.lab_role = "mq"
}

object Host "lab-dev-app01" {
  import "lab-fast-host"
  address = "lab-dev-app01"
  display_name = "DEV / APP 01"
  vars.lab_environment = "dev"
  vars.lab_role = "app"
}

object Host "lab-dev-web01" {
  import "lab-fast-host"
  address = "lab-dev-web01"
  display_name = "DEV / WEB 01"
  vars.lab_environment = "dev"
  vars.lab_role = "web"
}

object Host "lab-dev-db01" {
  import "lab-fast-host"
  address = "lab-dev-db01"
  display_name = "DEV / DB 01"
  vars.lab_environment = "dev"
  vars.lab_role = "db"
}
