template Service "lab-fast-service" {
  max_check_attempts = 2
  check_interval = 10s
  retry_interval = 3s
  enable_notifications = false
}

apply Service "middleware" {
  import "lab-fast-service"
  check_command = "lab-middleware-via-ssh"

  vars.lab_ssh_user = host.vars.lab_ssh_user
  vars.lab_remote_command = host.vars.lab_remote_command
  vars.lab_ssh_timeout = 5

  assign where host.vars.lab_managed
}
